# Generated by Django 4.2.7 on 2023-11-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubscribe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorysubscribe',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategorySubscribe',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
